### ISSUE TITLE
Replace use of `get_next_page_token` in the tap

### ISSUE THREAD

**Issue by laurentS** [MeltanoLabs/tap-github#215] opened 2023-06-09 11:00 UTC
Throughout CI runs, we are now getting this warning:
```
/home/runner/work/tap-github/tap-github/.venv/lib/python3.11/site-packages/singer_sdk/streams/rest.py:487:
   DeprecationWarning: `RESTStream.get_next_page_token` is deprecated and will not be used
   in a future version of the Meltano Singer SDK. Override `RESTStream.get_new_paginator` instead.
```

We should update the code to use the new method.

**Comment by JohannesRudolph** [comment] 2023-06-11 09:40
seems like a duplicate of #171

**Comment by laurentS** [comment] 2023-06-12 06:28
Oops. Indeed, sorry!

**Closed** 2023-06-12 06:29 UTC
Labels: skills:Python
